const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

/**
 * Charging session created after a user scans a QR code generated by admin for
 * a registered charging cable point and chooses a nominal / watt target.
 */
const ChargingSession = sequelize.define('ChargingSession', {
  sessionId: {
    type: DataTypes.STRING,
    primaryKey: true,
    allowNull: false
  },
  userId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  userName: {
    type: DataTypes.STRING,
    allowNull: true
  },
  cableId: {
    type: DataTypes.STRING,
    allowNull: false,
    references: {
      model: 'batteries',
      key: 'id'
    }
  },
  cableName: {
    type: DataTypes.STRING,
    allowNull: true
  },
  stationId: {
    type: DataTypes.STRING,
    allowNull: true,
    references: {
      model: 'stations',
      key: 'id'
    }
  },
  stationName: {
    type: DataTypes.STRING,
    allowNull: true
  },
  amount: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  requestedWatt: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  estimatedKwh: {
    type: DataTypes.DECIMAL(10, 3),
    allowNull: false,
    defaultValue: 0
  },
  pricePerKwh: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 2500
  },
  qrTokenSnapshot: {
    type: DataTypes.STRING,
    allowNull: true
  },
  status: {
    type: DataTypes.ENUM('pending', 'charging', 'completed', 'failed', 'cancelled'),
    defaultValue: 'charging',
    allowNull: false
  },
  startedAt: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  },
  completedAt: {
    type: DataTypes.DATE,
    allowNull: true
  }
}, {
  tableName: 'charging_sessions'
});

module.exports = ChargingSession;
